kafkaPool: nav-dev
mountPaths:
  - mountPath: /var/run/secrets/nais.io/service_user
    kvPath: /serviceuser/data/dev/srvsparkelidenter
env:
  - name: STS_BASE_URL
    value: http://security-token-service.default.svc.nais.local
  - name: KAFKA_BOOTSTRAP_SERVERS
    value: SSL://b27apvl00045.preprod.local:8443,SSL://b27apvl00046.preprod.local:8443,SSL://b27apvl00047.preprod.local:8443
