kafkaPool: nav-dev
env:
  - name: STS_BASE_URL
    value: http://security-token-service.default.svc.nais.local
  - name: KAFKA_BOOTSTRAP_SERVERS
    value: SSL://b27apvl00045.preprod.local:8443,SSL://b27apvl00046.preprod.local:8443,SSL://b27apvl00047.preprod.local:8443
envFrom:
  - gcp-sparkelidenter-credentials
gcp:
  type: POSTGRES_14
  name: sparkelidenter
  envVarPrefix: DATABASE
  tier: db-custom-2-7680
