apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: arbeidsgiveropplysninger
  namespace: tbd
  labels:
    team: tbd
spec:
  pool: nav-prod
  config:
    cleanupPolicy: delete
    minimumInSyncReplicas: 1
    partitions: 3
    replication: 2
    retentionBytes: -1
    retentionHours: 1440
  acl:
    - team: tbd
      application: sparkel-arbeidsgiver
      access: readwrite
    - team: helsearbeidsgiver
      application: helsearbeidsgiver-bro-sykepenger
      access: readwrite