kafkaPool: nav-dev
replicas:
  min: 1
  max: 1
spec:
  image: {{image}}
  port: 8080
  liveness:
    path: /is-alive
    initialDelay: 10
    timeout: 2
    periodSeconds: 30
    failureThreshold: 10
  readiness:
    path: /is-ready
    initialDelay: 10
    timeout: 2
    periodSeconds: 5
    failureThreshold: 10
