kafkaPool: nav-prod
azure:
  enabled: true
  tenant: nav.no
mountPaths:
- mountPath: /var/run/secrets/nais.io/service_user
  kvPath: /serviceuser/data/prod/srvsparkelvilkar
env:
- name: STS_URL
  value: https://sts.adeo.no/SecurityTokenServiceProvider/
- name: EGENANSATT_URL
  value: https://app.adeo.no/tpsws-aura/ws/EgenAnsatt/v1
- name: NOM_BASE_URL
  value: https://nom-api.intern.nav.no
- name: NOM_OAUTH_SCOPE
  value: api://prod-gcp.nom.nom-api/.default
