kafkaPool: nav-prod
mountPaths:
- mountPath: /var/run/secrets/nais.io/service_user
  kvPath: /serviceuser/data/prod/srvsparkelvilkar
env:
- name: STS_URL
  value: https://sts.adeo.no/SecurityTokenServiceProvider/
- name: EGENANSATT_URL
  value: https://app.adeo.no/tpsws-aura/ws/EgenAnsatt/v1
- name: AAREG_BASE_URL
  value: https://modapp.adeo.no/aareg-services/api