kafkaPool: nav-dev
azure:
  enabled: true
  tenant: trygdeetaten.no
env:
- name: MEDLEMSKAP_SCOPE
  value: api://ee472fd1-3621-4600-a6ac-69d3662e993f/.default
- name: MEDLEMSKAP_BASE_URL
  value: https://medlemskap-vurdering-sykepenger.dev.intern.nav.no/vurdering
