kafkaPool: nav-dev
azure:
  enabled: true
  tenant: trygdeetaten.no
env:
- name: MEDLEMSKAP_SCOPE
  value: api://2719da58-489e-4185-9ee6-74b7e93763d2/.default
- name: MEDLEMSKAP_BASE_URL
  value: https://medlemskap-vurdering-sykepenger.dev.intern.nav.no/vurdering
