kafkaPool: nav-dev
mountPaths:
- mountPath: /var/run/secrets/nais.io/service_user
  kvPath: /serviceuser/data/dev/srvsparkelnorg
env:
- name: NORG2_BASE_URL
  value: https://app-q1.adeo.no/norg2/api/v1
- name: SECURITY_TOKEN_SERVICE_URL
  value: http://security-token-service.default.svc.nais.local
- name: PDL_URL
  value: https://pdl-api.dev.intern.nav.no/graphql
