kafkaPool: nav-dev
replicas:
  min: 1
  max: 1
mountPaths:
  - mountPath: /var/run/secrets/nais.io/service_user
    kvPath: /serviceuser/data/dev/srvsparkelpleiepenge
azure:
  enabled: true
  tenant: trygdeetaten.no
env:
- name: INFOTRYGD_SCOPE
  value: api://6913c619-ba62-401e-a085-de99329bc432/.default
- name: INFOTRYGD_URL
  value: https://k9-infotrygd.dev.intern.nav.no
- name: STS_TOKEN_ENDPOINT
  value: http://security-token-service.default.svc.nais.local/rest/v1/sts/token
- name: ABAKUS_URL
  value: https://fpabakus.nais.preprod.local/fpabakus/api/ytelse/v1/hent-vedtatte
