kafkaPool: nav-prod
mountPaths:
  - mountPath: /var/run/secrets/nais.io/service_user
    kvPath: /serviceuser/data/prod/srvsparkelpleiepenge
azure:
  enabled: true
env:
- name: INFOTRYGD_SCOPE
  value: api://fb60234c-4d2a-4b2d-b5af-0ecbe7740944/.default
- name: INFOTRYGD_URL
  value: https://k9-infotrygd.intern.nav.no
- name: STS_TOKEN_ENDPOINT
  value: http://security-token-service.default.svc.nais.local/rest/v1/sts/token
- name: ABAKUS_URL
  value: https://fpabakus.nais.adeo.no/fpabakus/api/ytelse/v1/hent-vedtatte