kafkaPool: nav-dev
replicas:
  min: 1
  max: 1
azure:
  enabled: true
  tenant: nav.no
externalHosts:
  - pdl-api.dev-fss-pub.nais.io
env:
  - name: PDL_URL
    value: https://pdl-api.dev-fss-pub.nais.io/graphql
  - name: KAFKA_BOOTSTRAP_SERVERS
    value: SSL://b27apvl00045.preprod.local:8443,SSL://b27apvl00046.preprod.local:8443,SSL://b27apvl00047.preprod.local:8443