kafkaPool: nav-dev
mountPaths:
- mountPath: /var/run/secrets/nais.io/service_user
  kvPath: /serviceuser/data/dev/srvsparkeldkif
env:
- name: KAFKA_CONSUMER_GROUP_ID
  value: tbd-sparkel-dkif-v1
- name: KAFKA_RAPID_TOPIC
  value: tbd.rapid.v1
- name: STS_BASE_URL
  value: http://security-token-service.default.svc.nais.local
- name: DKIF_URL
  value: http://dkif.default.svc.nais.local

