kafkaPool: nav-dev
replicas:
  min: 1
  max: 1
mountPaths:
- mountPath: /var/run/secrets/nais.io/service_user
  kvPath: /serviceuser/data/dev/srvsputnik
env:
- name: FPSAK_BASE_URL
  value: http://fpsak.teamforeldrepenger.svc.nais.local
- name: STS_BASE_URL
  value: http://security-token-service.default.svc.nais.local
