kafkaPool: nav-dev
replicas:
  min: "1"
  max: "1"
envFrom:
  - gcp-sparkel-oppgave-endret-credentials
env:
- name: KAFKA_BOOTSTRAP_SERVERS_URL
  value: SSL://b27apvl00045.preprod.local:8443,SSL://b27apvl00046.preprod.local:8443,SSL://b27apvl00047.preprod.local:8443
- name: OPPGAVE_ENDRET_TOPIC
  value: aapen-oppgave-endret-v1-preprod
