kafkaPool: nav-dev
mountPaths:
- mountPath: /var/run/secrets/nais.io/service_user
  kvPath: /serviceuser/data/dev/srvsparkelaareg
env:
- name: KAFKA_CONSUMER_GROUP_ID
  value: tbd-sparkel-aareg-v1
- name: KAFKA_RAPID_TOPIC
  value: tbd.rapid.v1
- name: STS_BASE_SOAP_URL
  value: https://sts-q1.preprod.local/SecurityTokenServiceProvider/
- name: KODEVERK_BASE_URL
  value: http://kodeverk.default.svc.nais.local
- name: AAREG_BASE_URL
  value: https://modapp-q1.adeo.no/aareg-services/ArbeidsforholdService/v3
- name: ORGANISASJON_BASE_URL
  value: https://modapp-q1.adeo.no/ereg/ws/OrganisasjonService/v5