kafkaPool: nav-prod
mountPaths:
- mountPath: /var/run/secrets/nais.io/service_user
  kvPath: /serviceuser/data/prod/srvsparkelaareg
env:
- name: KODEVERK_BASE_URL
  value: http://kodeverk.default.svc.nais.local
- name: ORGANISASJON_BASE_URL
  value: https://modapp.adeo.no/ereg/api
- name: AAREG_BASE_URL_REST
  value: https://modapp.adeo.no/aareg-services/api
