kafkaPool: nav-dev
mountPaths:
  - mountPath: /var/run/secrets/nais.io/oracle/creds
    kvPath: oracle/data/dev/creds/sp_infotrygd_q-user
  - mountPath: /var/run/secrets/nais.io/oracle/config
    kvPath: oracle/data/dev/config/infotrygd_spq
env:
- name: DATABASE_SCHEMA
  value: INFOTRYGD_SPQ
