kafkaPool: nav-dev
mountPaths:
  - mountPath: /var/run/secrets/nais.io/oracle/creds
    kvPath: oracle/data/dev/creds/sp_infotrygd_q-user
  - mountPath: /var/run/secrets/nais.io/oracle/config
    kvPath: oracle/data/dev/config/infotrygd_spq
env:
- name: INFOTRYGDSP_URL
  value: jdbc:oracle:thin:@a01dbfl033.adeo.no:1521/cdcq
- name: INFOTRYGDSP_SCHEMA
  value: REST_READ_Q1
