kafkaPool: nav-dev
mountPaths:
- mountPath: /var/run/secrets/nais.io/service_user
  kvPath: /serviceuser/data/dev/srvsparkelinntekt
env:
- name: KAFKA_CONSUMER_GROUP_ID
  value: tbd-sparkel-inntekt-v1
- name: KAFKA_RAPID_TOPIC
  value: tbd.rapid.v1
- name: INNTEKTSKOMPONENT_BASE_URL
  value: https://app-q1.adeo.no/inntektskomponenten-ws/rs
