kafkaPool: nav-dev
mountPath:
- mountPath: /var/run/secrets/nais.io/service_user
  kvPath: /serviceuser/data/dev/srvsparkelarena
env:
- name: KAFKA_CONSUMER_GROUP_ID
  value: tbd-sparkel-arena-v1
- name: KAFKA_RAPID_TOPIC
  value: tbd.rapid.v1
- name: STS_URL
  value: https://sts-q2.preprod.local/SecurityTokenServiceProvider/
- name: YTELSESKONTRAKT_BASE_URL
  value: https://arena-q2.adeo.no/ail_ws/Ytelseskontrakt_v3
- name: MELDEKORT_UTBETALINGSGRUNNLAG_ENDPOINTURL
  value: https://arena-q2.adeo.no/ail_ws/MeldekortUtbetalingsgrunnlag_v1
