name: Aiven-config

on:
  push:
    branches:
      - main
    paths:
      - 'config/arbeidsgiver/aiven-dev.yml'

jobs:
  deployDev:
    name: apply kafka-topic i dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: config/arbeidsgiver/aiven-dev.yml