name: Deploy
on:
  push:
    branches:
      - main
env:
  DOCKER_IMAGE_PREFIX: docker.pkg.github.com/${{ github.repository }}
  SNYK_ORG: tbd-ty7

jobs:
  generate_build_matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v1
      - name: cache gradle wrapper
        uses: actions/cache@v2
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}
      - id: set-matrix
        run: |
          MATRIX=$(./gradlew -q buildMatrix --console=plain)
          echo Setting matrix to $MATRIX
          echo "::set-output name=matrix::$MATRIX"

  build:
    needs: generate_build_matrix
    name: build
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(needs.generate_build_matrix.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '14.x'
      - name: cache gradle deps
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('**/*.gradle', '**/*.gradle.kts', 'gradle.properties') }}
      - name: cache gradle wrapper
        uses: actions/cache@v2
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}
      - name: test and build
        run: ./gradlew ${{ matrix.project }}::test ${{ matrix.project }}::build
      - name: Check app.jar existence
        id: app_jar
        uses: andstor/file-existence-action@v1
        with:
          files: "${{ matrix.project }}/build/libs/app.jar"
      - name: create docker tag
        if: steps.app_jar.outputs.files_exists == 'true'
        run: |
          echo "TAG=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV
          echo "IMAGE=$DOCKER_IMAGE_PREFIX/${{ matrix.project }}:$TAG" >> $GITHUB_ENV
      - name: build docker image
        if: steps.app_jar.outputs.files_exists == 'true'
        run: docker build ${{ matrix.project }} --pull -t ${{ env.IMAGE }} -f Dockerfile
      - name: push docker image
        if: steps.app_jar.outputs.files_exists == 'true'
        run: |
          docker login --username "$GITHUB_REPOSITORY" -p ${{ secrets.GITHUB_TOKEN }} https://docker.pkg.github.com
          docker push ${{ env.IMAGE }}

  snyk:
    name: check vulnerabilities
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Gradle vulnerability check
        uses: snyk/actions/gradle-jdk12@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --all-sub-projects --org=${{ env.SNYK_ORG }} --fail-on=all
          command: monitor