name: Deploy
on:
  registry_package:
    types: [ published ] # event payload: https://docs.github.com/en/developers/webhooks-and-events/webhook-events-and-payloads#package
jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Dump Github Context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"